### ISSUE TITLE
MD5 hash collision 

### ISSUE THREAD

**Issue by Kuo-TingKai** [jiachengx/ironmen2020#2]
MD5作為checksum演算法似乎存在雜湊碰撞的可能，我之後想要把它替換成其他的checksum實作

**Comment by jiachengx** [comment]
您可以嘗試其他演算法來驗證您的假設，但我所做的練習是當時的其中一個應用. 重點不是演算法本身，而是您必須去了解為什麼要做這個測試驗證.

Kuo Ting-Kai ***@***.***> 於 2023年1月22日 週日 上午12:58寫道：
